repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-yaml
- repo: https://github.com/pre-commit/pre-commit
  rev: v2.6.0
  hooks:
  - id: validate_manifest
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
- repo: https://github.com/henryykt/pre-commit-perl
  rev: v0.0.4
  hooks:
    - id: perltidy
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.5
  hooks:
    - id: reorder-python-imports
      args: [--py3-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.2
  hooks:
    - id: pyupgrade
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.11.0
  hooks:
    - id: setup-cfg-fmt
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
    - id: mypy
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.23.2
  hooks:
    - id: markdownlint
