- id: check-ipv6-case
  name: Check IPv6 case
  description: Check IPv6 literals are lower case
  entry: hooks/check-ipv6-case.pl
  language: script
- id: check-dns-config
  name: Check DNS config
  description: Check bind9 DNS server configuration and zone files
  pass_filenames: false
  language: docker
  entry: /usr/bin/check-dns-config
