- id: check-ipv6-case
  name: Check IPv6 case
  description: Check IPv6 literals are lower case
  entry: check-ipv6-case.pl
  language: perl
- id: check-macaddr-case
  name: Check MAC address case
  description: Check MAC addresses are lower case
  entry: check-macaddr-case.pl
  language: perl
- id: check-dhcphost-format
  name: Check DHCP host entry format
  description: Check DHCP host entries match standard format
  entry: check-dhcphost-format
  language: python
- id: check-dns-cname
  name: Check DNS CNAME
  description: Check DNS zone file for CNAME pointing to IP
  entry: check-dns-cname
  language: python
- id: check-dns-config
  name: Check DNS config
  description: Check bind9 DNS server configuration and zone files
  pass_filenames: false
  language: docker
  entry: check-dns-config
- id: check-ascii
  name: Require ASCII
  description: Ensure only printable ASCII Chars
  entry: check-ascii
  language: python
- id: check-dhcp-config
  name: Check dhcp config
  description: Check ISC DHCP server configuration files
  pass_filenames: false
  language: docker
  entry: check-dhcp-config
- id: check-dns-serial
  name: Check DNS serial
  language: script
  entry: hooks/check-dns-serial.sh
  pass_filenames: false
