repos:
- repo: https://github.com/pre-commit/pre-commit
  rev: v2.14.0
  hooks:
  - id: validate_manifest
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-yaml
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args:
    - --quiet-level=2
    - --check-filenames
    - --check-hidden
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
  - id: yamllint
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks.git
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/pre-commit
  rev: v2.14.0
  hooks:
  - id: validate_manifest
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.28.1
  hooks:
  - id: markdownlint
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
- repo: https://github.com/henryykt/pre-commit-perl
  rev: v0.0.4
  hooks:
  - id: perltidy
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.24.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    additional_dependencies: [types-termcolor==1.1.1]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.17.0
  hooks:
  - id: setup-cfg-fmt
