repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-yaml
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
- repo: https://github.com/henryykt/pre-commit-perl
  rev: v0.0.4
  hooks:
    - id: perltidy
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.23.2
  hooks:
    - id: markdownlint
